services:
- type: web
  name: WanderMatch
  runtime: python-3.12.9
  repo: https://github.com/TongmengXie/Encode_AI
  branch: deploy
  plan: free
  region: frankfurt
  buildCommand: bash build.sh
  startCommand: bash start.sh
  envVars:
      - key: PYTHON_VERSION
        value: 3.12.9

# envVarGroups:
#   - name: conc-settings
#     envVars:
#       - key: CONCURRENCY
#         value: 2
#       - key: SECRET
#         generateValue: true
#   - name: stripe
#     envVars:
#       - key: STRIPE_API_URL
#         value: https://api.stripe.com/v2